name: Lint
on:
  push:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Python Black Lint Check
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: pip install black nbqa
      - name: Run Black on Python files
        run: black --check $(find . -type f -name "*.py")
