name: Run Tests
on:
  workflow_call:
    inputs:
      test-folders:
        description: "Array of test folders to run"
        required: false
        type: "string"
        default: '["database", "logic", "endpoints", "sdk"]'
      python-version:
        description: "Python version to use"
        required: false
        type: "string"
        default: "3.10"
      additional-python-dependencies:
        description: "Additional pip packages to install"
        required: false
        type: "string"
        default: "openai requests agixtsdk qrcode==7.4.2"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-folder: ${{ fromJSON(inputs.test-folders) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          # Install additional dependencies if specified
          if [ -n "${{ inputs.additional-python-dependencies }}" ]; then
            python -m pip install ${{ inputs.additional-python-dependencies }}
          fi
          # Install from requirements.txt if it exists
          if [ -f requirements.txt ]; then 
            python -m pip install -r requirements.txt
          fi
          # Try to install package in development mode
          # Handle potential errors with the package installation
          python -m pip install -e . || echo "Warning: Package installation failed, tests may not run correctly"
      - name: Run tests for ${{ matrix.test-folder }}
        id: run_tests
        run: |
          echo "Running tests in tests/${{ matrix.test-folder }}"
          python -m pytest tests/${{ matrix.test-folder }} \
            --cov=./ \
            --cov-report=xml:coverage-${{ matrix.test-folder }}.xml \
            -v
      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.test-folder }}
          path: coverage-${{ matrix.test-folder }}.xml
